### ISSUE TITLE
Fantastic

### ISSUE THREAD

**Issue by manuel-uberti** [lassekongo83/amber-theme#1]
Sorry, this is not an issue of course. I tried this theme and although you wrote in the README that it is not finished, it already looks fantastic.

Speaking as a long-time fan of your Zuki* themes, you could be outshining yourself here. :)

Keep up the awesome work!

**Comment by lassekongo83** [comment]
Thank you. The theme is almost finished. Just have some minor stuff to fix on the GTK3/Shell theme and some medium stuff to finish on the GTK2 theme.
