### ISSUE TITLE
The highlight effect for the toggle buttons seems cut

### ISSUE THREAD

**Issue by kepler2** [lassekongo83/amber-theme#12]
Greetings!

I've noticed that the highlight effect for the toggle buttons seems cut.

Please see the screenshots below.

Effect seems cut (at the top and bottom)

![1](https://user-images.githubusercontent.com/18610924/52197997-1e35d680-286a-11e9-88cf-dc5a231d1138.png)

Effect looks OK on sliders (effect is round):

![2](https://user-images.githubusercontent.com/18610924/52198087-60f7ae80-286a-11e9-8e8a-4ced638cf272.png)

- OS/version: XFCE 4.12 / Linux 4.19.18-1-lts x86_64

**Comment by lassekongo83** [comment]
Which application is that?

**Comment by kepler2** [comment]
> Which application is that?

xfce4-notifyd-config
