### ISSUE TITLE
Java application menu unreadable

### ISSUE THREAD

**Issue by manuel-uberti** [lassekongo83/amber-theme#13]
### Describe the issue

In [VisualVM](https://visualvm.github.io/), which is a Java application, the menu is unreadable. See Screenshots for details.

### Screenshot(s)

![1](https://user-images.githubusercontent.com/8199224/52961574-896bc680-339b-11e9-9347-179d38ede5e4.png)

![2](https://user-images.githubusercontent.com/8199224/52961581-8c66b700-339b-11e9-8d05-2b3ceecab95e.png)

### Versions

- OS/version: Ubuntu 18.04
- GTK+ and/or application versions: GTK+ Version 3.22.30

**Comment by lassekongo83** [comment]
Testing in VisualVM 1.4.2, and it has a completely different interface for me (non-gtk). Did you install it with any flags or changed any settings somewhere?

**Comment by manuel-uberti** [comment]
No, I'm just running the executable in the archive downloaded from the official site.

**Comment by lassekongo83** [comment]
Can you test this? 
1. Open `gtk-2.0/gtkrc`
2. CTRL+F `style "menubar-menuitem" {`
3. Change `@fg_color` to `@text_color_dark`
4. Reload the application and see if the menus have the correct color.

**Comment by manuel-uberti** [comment]
Done:
```
style "menubar-menuitem" {
    xthickness     = 3

    bg[PRELIGHT]   = @selected_bg_color
    bg[SELECTED]   = @selected_bg_color
    fg[NORMAL]     = @text_color_dark
    fg[PRELIGHT]   = @selected_fg_color
    fg[SELECTED]   = @selected_fg_color
    text[NORMAL]   = @text_color_dark
    text[PRELIGHT] = @selected_fg_color
    text[SELECTED] = @selected_fg_color

	engine "murrine" {
		  lightborder_shade = 1.0
    }
}
```
There are two occurrences of `@fg_color`. I changed both. Same result in VisualVM, though.

**Comment by manuel-uberti** [comment]
One thing I noticed, with `visualvm` installed via `apt` (version `1.3.9`), the menu looks fine.

![screenshot](https://user-images.githubusercontent.com/8199224/52999061-1eff6880-3425-11e9-8ca8-95bd80dd0bd3.png)

**Comment by lassekongo83** [comment]
My guess is that `_JAVA_OPTIONS` is properly configured when it is installed through `apt`. https://wiki.archlinux.org/index.php/java#GTK_LookAndFeel (Though, I couldn't get that to work.)

Don't really know how it works for source installed java applications.

**Comment by manuel-uberti** [comment]
Thank you. I'll give it a try.

We can close this issue, then, since it works perfectly fine with the version from `apt` and so it is not related to your theme.
