### ISSUE TITLE
Rambox application menu unreadable

### ISSUE THREAD

**Issue by manuel-uberti** [lassekongo83/amber-theme#14]
### Describe the issue

In [Rambox](https://rambox.pro/#home) the menu is unreadable. See Screenshots for details.

### Screenshot(s)

![screenshot](https://user-images.githubusercontent.com/8199224/53329501-7ea9b800-38ec-11e9-9262-1791c4514a56.png)

### Versions

- OS/version: Ubuntu 18.04.02
- GTK+ and/or application versions: GTK+ Version 3.22.30

**Comment by lassekongo83** [comment]
Seems to be an issue with the Electron version used in rambox from the information I could find.
Rambox 0.6.3 uses Electron: 2.0.14. This issue should be fixed with Electron `3.0.1` (or `4.0.1`?)
https://github.com/ubuntu/yaru/issues/969
https://github.com/shiftkey/desktop/issues/114

**Comment by manuel-uberti** [comment]
Great, thanks debugging this. I am closing the issue since it's not a problem with Amber then.
