### ISSUE TITLE
Atom IDE - Menu items have very dark color making them barely visible

### ISSUE THREAD

**Issue by kepler2** [lassekongo83/amber-theme#17]
Hello!

Great theme as always :). Thanks for your work.

I've noticed something in the Atom IDE - https://atom.io/

The menu items are not visible when the window is focused. It happens with all the integrated Atom themes.

**Screenshot:**

![atom editor](https://user-images.githubusercontent.com/18610924/59568486-df1f5980-9083-11e9-8f9c-00a8644251df.png)

If the window loses focus, the menu items are visible, but with a dark gray color? 

![atom 2](https://user-images.githubusercontent.com/18610924/59568502-2e658a00-9084-11e9-9a41-38ef8a2a0c3d.png)

- OS/version: MX Linux 18.3, Kernel: 4.19.0-5-amd64 x86_64
- GTK+ and/or application versions: Atom version 1.38.1, using latest Amber Theme version.

**Comment by kepler2** [comment]
Hey :)

I have attached a video:

https://i.imgur.com/wE8nMOO.mp4

**Comment by lassekongo83** [comment]
Seems to be related to: https://github.com/lassekongo83/amber-theme/issues/14

Upgrade Electron to 3.0.1 or later.
