### ISSUE TITLE
Nautilus left pane

### ISSUE THREAD

**Issue by fblais** [lassekongo83/amber-theme#22]
Hi.
The top of Nautilus left pane is not aligned with the tab's top.
Don't know if it's a bug though.

![image](https://user-images.githubusercontent.com/28492426/121255221-273f7400-c879-11eb-9b7c-37c1caefe60c.png)

- OS/version: Debian testing
- Gnome-shell: 3.38.4

Thanks!

**Comment by lassekongo83** [comment]
Not a bug.
