### ISSUE TITLE
Dash to Dock theme

### ISSUE THREAD

**Issue by manuel-uberti** [lassekongo83/amber-theme#4]
I don't know if this can help with the development, but this is what I see using `amber-theme`:

![amber](https://user-images.githubusercontent.com/8199224/44907884-e2766e00-ad19-11e8-9e1c-00272855f925.png)

However, if I use `zukitre` with the same settings for Dash to Dock I see this:

![zukitree](https://user-images.githubusercontent.com/8199224/44907918-fcb04c00-ad19-11e8-91b9-26d3ce2f2155.png)

These are the Appearance settings for Dash to Dock I am using:

![dashtodock](https://user-images.githubusercontent.com/8199224/44907961-24071900-ad1a-11e8-923e-a280964436fe.png)

I  am running Ubuntu 18.04.1 LTS, with GNOME Shell 3.28.3, and GTK+ Version 3.22.30.

**Comment by lassekongo83** [comment]
I don't know, but it looks like you aren't using the latest version from the master branch. That issue was fixed a couple of weeks ago.

**Comment by manuel-uberti** [comment]
I upgraded few minutes ago:
```
commit cf45539b09b9e920223fc5ec106a78b18eee6058 (HEAD -> master, origin/master, origin/HEAD)
Author: lassekongo83 <lassekongo83@users.noreply.github.com>
Date:   Fri Aug 31 12:10:14 2018 +0200

    Use a single selected color in assets.svg
```

**Comment by lassekongo83** [comment]
Something must be wrong with your update then. Your screenshot shows that you're using an older version (unless you've manually made some changes to the theme). Try a fresh install by first removing `/usr/share/themes/amber-theme` and/or `~/.themes/amber-theme`.

**Comment by manuel-uberti** [comment]
You're right. I remove `~/.themes/amber-theme` and re-cloned the repository. It works now. Thanks a lot.
