### ISSUE TITLE
Separator on the left of Gnome3 app window buttons

### ISSUE THREAD

**Issue by logix2** [lassekongo83/amber-theme#6]
There's a separator at the left of Gnome 3 applications window buttons, like Nautilus or Gedit: https://i.imgur.com/YohfAN3.png

Is this intentional or a bug? I remember seeing this back when themes broke with basically every Gtk3 update, and thus my bug report. I'm using Ubuntu 18.10 with Gtk 3.24.1 and the latest Amber theme (master).

**Comment by lassekongo83** [comment]
It's intentional. ([the code](https://github.com/lassekongo83/amber-theme/blob/master/gtk-3.0/_common.scss#L3735))

**Comment by logix2** [comment]
Got it, thanks!
