### ISSUE TITLE
Double indicators on Ubuntu Dock

### ISSUE THREAD

**Issue by logix2** [lassekongo83/amber-theme#7]
Ubuntu Dock (a fork of Dash to Dock) defaults to displaying "dots" as the running indicator, and there's no option to change this. As a result, double running indicators appear when using the Amber theme for Gnome Shell: https://i.imgur.com/rdFDErG.jpg

This happens in both Ubuntu 18.04 and 18.10.

**Comment by lassekongo83** [comment]
Unfortunately the Ubuntu dock have hardcoded parts that can't be changed by a theme. I would just suggest that you replace the default dock with `dash to dock` instead as it has more settings. Then you can get rid of those dots by going into the settings > appearance and change the first combobox value to `standard`.

**Comment by logix2** [comment]
Indeed... thanks!
